[build]
  command = "bun run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # 如果需要指定 Bun 版本，取消下面一行的注释
  # BUN_VERSION = "1.0.0"

# 构建优化设置
[build.processing]
  skip_processing = true

# 环境特定配置
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"

# Bun 构建插件 (如果需要)
# [[plugins]]
#   package = "@netlify/plugin-bun"

# SPA 路由支持 - 解决 404 问题的关键
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 更精确的路由配置 (备选方案)
[[redirects]]
  from = "/blog/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/about/*"
  to = "/index.html"
  status = 200

# 缓存优化头部
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 安全头部
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 如果使用图片优化
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=3600"
